import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import i18n from './i18n'
import { vReveal } from './directives/reveal'
import './assets/styles/tokens.scss'
import './style.css'

const app = createApp(App)
app.use(createPinia())
app.use(router)
app.use(i18n)
app.directive('reveal', vReveal)

// 全局错误兜底：Vue 组件渲染/事件处理中的未捕获异常
app.config.errorHandler = (err, _instance, info) => {
  console.error('[vue-error]', info, err)
}
// 全局 JS 异常 & 未捕获的 Promise reject，避免静默丢失
window.addEventListener('error', (e) => {
  console.error('[window-error]', e.message, e.error)
})
window.addEventListener('unhandledrejection', (e) => {
  console.error('[unhandled-rejection]', e.reason)
})

// R31: PWA — register the service worker generated by vite-plugin-pwa. The
// `virtual:pwa-register` module is only available because of the plugin in
// vite.config.ts. We swallow the import error in dev mode so the page still
// renders when the dev server hasn't materialised the virtual module.
if ('serviceWorker' in navigator) {
  import('virtual:pwa-register')
    .then(({ registerSW }) => {
      registerSW({ immediate: true })
    })
    .catch(() => {
      // dev mode — SW is served by devOptions instead.
    })
}

app.mount('#app')
