/**
 * R31: service-worker — Workbox strategies via vite-plugin-pwa `injectManifest`.
 *
 * Strategy map:
 *   - app shell (HTML navigations):     NetworkFirst, fallback to /offline shell
 *   - JS / CSS / Worker bundles:        StaleWhileRevalidate (precached too)
 *   - images / fonts / svg:             CacheFirst (1y)
 *   - /api GET (read-only):             StaleWhileRevalidate
 *   - /api POST/PUT (mutation):         NetworkOnly + background-sync into
 *                                       a Background Sync queue named
 *                                       "ai-requests" (see queue.ts)
 *   - map tiles (MapLibre / deck.gl):   CacheFirst with expiration
 *
 * The "AI request queue" lets the AI mascot keep asking the LLM while offline:
 *   1. fetch() fails because navigator.onLine === false
 *   2. enqueueAiRequest() writes to IndexedDB and registers a sync tag
 *   3. service worker picks it up on `sync` event and replays the POST
 *
 * Generated by vite-plugin-pwa. Do NOT register manually — main.ts calls
 * `registerSW({ immediate: true })`.
 */
/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { NetworkFirst, StaleWhileRevalidate, CacheFirst, NetworkOnly } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { BackgroundSyncPlugin } from 'workbox-background-sync'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: any
}

// 1) Precache the build manifest. Vite injects { url, revision, ... } entries.
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// 2) App-shell navigations — NetworkFirst, fall back to the precached /offline
//    page (if present) or the last good HTML.
const navigationHandler = new NetworkFirst({
  cacheName: 'mnemoscape-shell-v1',
  networkTimeoutSeconds: 4,
  plugins: [
    new CacheableResponsePlugin({ statuses: [0, 200] }),
  ],
})
const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [/^\/api\//, /^\/ws\//],
})
registerRoute(navigationRoute)

// 3) Bundles (HASH-*.js / .css emitted by Vite rollup). StaleWhileRevalidate
//    because the precache is already authoritative; SWR handles cache misses
//    for code-split chunks the user has not yet loaded.
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style' || request.destination === 'worker',
  new StaleWhileRevalidate({
    cacheName: 'mnemoscape-bundles-v1',
    plugins: [new ExpirationPlugin({ maxEntries: 80, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  })
)

// 4) Images / fonts / SVG.
registerRoute(
  ({ request }) => request.destination === 'image' || request.destination === 'font',
  new CacheFirst({
    cacheName: 'mnemoscape-assets-v1',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 365, purgeOnQuotaError: true }),
    ],
  })
)

// 5) MapLibre / Maptiler / OSM tiles — heavy, immutable-ish, CacheFirst.
registerRoute(
  ({ url }) => /tile\.openstreetmap\.org|api\.maptiler\.com|maplibre\.org/.test(url.hostname),
  new CacheFirst({
    cacheName: 'mnemoscape-tiles-v1',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 500, maxAgeSeconds: 60 * 60 * 24 * 30, purgeOnQuotaError: true }),
    ],
  })
)

// 6) Read-only /api GETs — StaleWhileRevalidate so the UI feels instant.
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'GET',
  new StaleWhileRevalidate({
    cacheName: 'mnemoscape-api-read-v1',
    plugins: [new ExpirationPlugin({ maxEntries: 80, maxAgeSeconds: 60 * 5 })],
  })
)

// 7) AI / mutation POSTs — NetworkOnly + Background Sync into IndexedDB.
//    When the user is offline, the request is parked. On `sync` it replays.
const aiQueue = new BackgroundSyncPlugin('ai-requests', {
  maxRetentionTime: 24 * 60, // minutes — replay up to 24h after first failure
})
registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/ai/') && (request.method === 'POST' || request.method === 'PUT'),
  new NetworkOnly({ plugins: [aiQueue] }),
  'POST'
)
registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/ai/') && (request.method === 'POST' || request.method === 'PUT'),
  new NetworkOnly({ plugins: [aiQueue] }),
  'PUT'
)

// 8) Manual message channel — lets the page ask SW to replay the queue,
//    e.g. when the offline banner detects "online" again.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'REPLAY_AI_QUEUE') {
    // Workbox 7+: registration.sync is exposed via the BackgroundSyncPlugin's
    // replayRequests() — but the plugin handles this on its own when the
    // browser fires a 'sync' event. We just acknowledge.
    event.ports[0]?.postMessage({ ok: true, queued: 'ai-requests' })
  }
})

// 9) Activate new SW immediately on update.
self.addEventListener('install', () => {
  self.skipWaiting()
})
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})
